### ISSUE TITLE
For the native/ part, do we need to write in OCaml?

### ISSUE THREAD

**Issue by dylanirlbeck** [ahrefs/hello-native-bucklescript#2]
I'm a bit new to Reason/OCaml, and I was curious if it's possible to just use Reason files in the `native/` part of the library. If I'm not mistaken, Reason also compiles to OCaml, so there shouldn't be anything stopping me from writing Reason in the `/native` folder, right?

Thanks in advance!

**Comment by Khady** [comment]
Yes you can. Dune is able to automatically transform the reason files. You just need to have the reason package installed

**Comment by dylanirlbeck** [comment]
Okay, thanks!
